export enum NotificationTypes {
  AccountUpdated = 'AccountUpdated',
  AccountMemberCreated = 'AccountMemberCreated',
  AccountMemberUpdated = 'AccountMemberUpdated',
  ENSNodeCreated = 'ENSNodeCreated',
  ENSNodeUpdated = 'ENSNodeUpdated',
  GatewayBatchCreated = 'GatewayBatchCreated',
  GatewayBatchUpdated = 'GatewayBatchUpdated',
  P2PPaymentChannelCreated = 'P2PPaymentChannelCreated',
  P2PPaymentChannelUpdated = 'P2PPaymentChannelUpdated',
  P2PPaymentDepositCreated = 'P2PPaymentDepositCreated',
  P2PPaymentDepositUpdated = 'P2PPaymentDepositUpdated',
  PaymentHubCreated = 'PaymentHubCreated',
  PaymentHubUpdated = 'PaymentHubUpdated',
  PaymentHubBridgeCreated = 'PaymentHubBridgeCreated',
  PaymentHubBridgeUpdated = 'PaymentHubBridgeUpdated',
  PaymentHubDepositCreated = 'PaymentHubDepositCreated',
  PaymentHubDepositUpdated = 'PaymentHubDepositUpdated',
  PaymentHubPaymentCreated = 'PaymentHubPaymentCreated',
  TransactionUpdated = 'TransactionUpdated',
}
