export enum NotificationTypes {
  AccountUpdated = 'AccountUpdated',
  AccountMemberCreated = 'AccountMemberCreated',
  AccountMemberUpdated = 'AccountMemberUpdated',
  ENSSubNodeCreated = 'ENSSubNodeCreated',
  ENSSubNodeUpdated = 'ENSSubNodeUpdated',
  GatewayBatchCreated = 'GatewayBatchCreated',
  GatewayBatchUpdated = 'GatewayBatchUpdated',
  P2PPaymentChannelCreated = 'P2PPaymentChannelCreated',
  P2PPaymentChannelUpdated = 'P2PPaymentChannelUpdated',
  PaymentHubCreated = 'PaymentHubCreated',
  PaymentHubUpdated = 'PaymentHubUpdated',
  PaymentHubBridgeCreated = 'PaymentHubBridgeCreated',
  PaymentHubBridgeUpdated = 'PaymentHubBridgeUpdated',
  PaymentHubDepositCreated = 'PaymentHubDepositCreated',
  PaymentHubDepositUpdated = 'PaymentHubDepositUpdated',
  PaymentHubPaymentCreated = 'PaymentHubPaymentCreated',
}
