export enum NotificationTypes {
  AccountUpdated = 'AccountUpdated',
  AccountMemberCreated = 'AccountMemberCreated',
  AccountMemberUpdated = 'AccountMemberUpdated',
  ENSSubNodeCreated = 'ENSSubNodeCreated',
  ENSSubNodeUpdated = 'ENSSubNodeUpdated',
  P2PPaymentChannelCreated = 'P2PPaymentChannelCreated',
  P2PPaymentChannelUpdated = 'P2PPaymentChannelUpdated',
  PaymentHubCreated = 'PaymentHubCreated',
  PaymentHubUpdated = 'PaymentHubUpdated',
  PaymentHubDepositCreated = 'PaymentHubDepositCreated',
  PaymentHubDepositUpdated = 'PaymentHubDepositUpdated',
  PaymentHubPaymentCreated = 'PaymentHubPaymentCreated',
  RelayedTransactionCreated = 'RelayedTransactionCreated',
  RelayedTransactionUpdated = 'RelayedTransactionUpdated',
}
