name: Check if package version is updated

on:
  push:
  # pull_request:
  #   branches:
  #     - master
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Check if version has been updated
        id: check
        uses: del-systems/check-if-version-bumped@v1
         with:
          token: ${{ secrets.GITHUB_TOKEN }}