name: CodeQL scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Initialize CodeQL
        uses: github/codeql-action/init@807578363a7869ca324a79039e6db9c843e0e100
        with:
          queries: security-and-quality
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@807578363a7869ca324a79039e6db9c843e0e100